name: Deploy MultiDocker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test
 
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client-10-14 ./client
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx-10-14 ./nginx
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-server-10-14 ./server
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker-10-14 ./worker
 
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-client-10-14
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx-10-14
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-server-10-14
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker-10-14
 